### ISSUE TITLE
渲染图形的鼠标事件触发存在问题

### ISSUE THREAD

**Issue by mgzu** [PengJiyuan/omg#11]
`    //circle是一个对象，以下是circle的构造函数

      function Circle(x, y, radius, color, name, value, id) {
            this.x = x;
            this.y = y;
            this.radius = radius;
            this.color = color;
            this.name = name;
            this.value = value;
            this.id = id;
      }

      //初始化圆并添加到canvas中
      function createArc(circle) {
            var arc = world.arc({
                x: (circle.x*stage.width).toFixed(1),
                y: (circle.y*stage.height).toFixed(1),
                radius: circle.radius*10,
                color: circle.color,
                style: 'fill'
            }).on('mouseenter mousemove', function() {
                tip.style.display = 'block';
                setValue({
                    title: '测点',
                    color: circle.color,
                    name: circle.name,
                    value: circle.value,
                //  id: circle.id,
                });
                console.log(circle.value)
                world.element.style.cursor = 'pointer';
                var x = world.utils.getPos().x + 20;
                var y = world.utils.getPos().y + 20;
                tip.style.left = x + 'px';
                tip.style.top = y + 'px';
            }).on('mouseleave', function() {
                tip.style.display = 'none';//隐藏tip
                world.element.style.cursor = 'default';
            }).on('mousedown', function() {
                console.log('image3');
            }).config({
                drag: tr,
                changeIndex: false
            });
            stage.addChild(arc);
        }  `

以上是我的代码，想要达到的效果是，鼠标移入到圆上，在canvas中显示圆的信息（提示信息参考的是big_data的demo）。而测试的时候，发现当圆较小时，无法正确的触发鼠标事件，所以将圆的半径*10查看，当鼠标移入圆下半部分时还是无法触发，而鼠标事件的触发区域大概比正常区域提高了50px。
PS：第一次写lssuse，没有上传图片，望见谅

**Comment by mgzu** [comment]
先谢谢作者@PengJiyuan 
上面没说详细，我再补充一点
使用的版本是1.3.5
用一张图片做背景图，在背景图上添加圆点，这个可能会存在影响，以下是图片的渲染和循环添加圆点

        var image = world.image({
            startX: 0,
            startY: 0,
            width: stage.width,
            height: stage.height,
            src: imgsrc
        }).config({
            bg: true,
            fixed: true
        });;
        stage.addChild(image);
        //画圆
        function drawArc(){
            for(var i = 0;i < circles.length; i++) {
                createArc(circles[i]);
            }
        }
        drawArc()
        stage.show()

PS：希望作者能够补充API（傻瓜教程），菜鸡表示readme看的亿脸懵逼

**Comment by PengJiyuan** [comment]
我把代码重构了一下，把版本升级到了3.0，代码捋顺了一下，增加了对retina屏幕的处理，api基本都没有变化，除了初始化的时候少了一步init(正在考虑是否需要重新加上init).  你可以用最新的3.0beta试试，看是否还有问题，demo中用的库都是最新的3.0.

看了一下你的代码，感觉是没问题的 (config里的bg属性是不起作用的，可以设置zindex ，把要当作背景的元素设为最小)。

而且圆的大小是不影响鼠标事件的，我的demo里的圆半径是1的时候也是正常触发的，你用的是什么浏览器，难道是有兼容问题？

如果急着解决的话，你可以把你的源码邮件给我，我帮你看一下。

感谢你能发现这个有意思的小库，目前这个库实现了一些最基本的功能，以后还有很多想法，希望你能保持关注~

**Comment by mgzu** [comment]
谢谢@PengJiyuan 
首先，demo的效果在chrome浏览器中并没有影响，所以应该并不是浏览器兼容问题。我尝试了使用3.0版本，遗憾的是并没有解决这个问题。我想到是否是引用的JS之间存在着冲突（引用的JS太多了），我尝试删除了JS、CSS后刷新页面，终于在移除bootstarp的css（万万没想到是它在捣蛋）后，鼠标事件恢复正常。
现在又有一个问题是，我给canvas添加点击事件，会向页面点击的坐标添加圆点，这时如果取消操作（我使用了计时器，取消会移除数组最后一个元素，调用stage.clear()，然后重绘canvas），页面会重绘，但是没有效果，需要移除的元素依然存在（可能是没有移除child）
测试代码以打包发送至您的邮箱

**Comment by PengJiyuan** [comment]
1. 关于removeChild方法，这是个很好的建议。没有removeChild的时候，其实可以通过手动改变world.objects (canvas渲染的其实是objects数组里的一堆对象)。 感谢建议，我会加上移除第一个元素，移除最后一个元素，移除选中元素，移除所有元素。但是关于您邮件里说的移除所有临时元素，这个需要一种别的实现思路，下边会讲。

2. 您邮件里提到，在addChild里添加一个参数（默认为false），如果为true，则为临时元素。这个需求是您在实际渲染的时候，背景图片不需要重复重绘。但是canvas本身是一个整体，clear的是整个canvas画布，所以如果背景图片需要显示，必须要重绘。这个临时元素其实就是我之后想做的分层绘制，就是构建多个canvas画布叠加，这样您说的这个临时元素其实也就解决了，只重绘某些元素。

3. 关于clear和show，现在的clear和show其实功能很简单和单一，clear清理画布，show绘制画布并且触发事件监控（如果单纯的重绘的话，使用redraw方法）。这两个方法确实也需要好好斟酌完善一下。

4. 关于内置特效，比如闪烁，旋转，抖动等，本来最开始我是内置了一些效果的，比如旋转。但是旋转之后，很难判断点是否在旋转后的图形内，所以就临时删除了。这个需要找出一个更合理的判断点在图形内的方法，再来添加内置特效。
