### ISSUE TITLE
希望给draw方法中的drawImage添加try...catch...

### ISSUE THREAD

**Issue by mgzu** [PengJiyuan/omg#13]
如题，当image的src并不存在时，会触发Uncaught DOMException（chrome），所以希望能够在drawImage上添加相应的try...catch...
PS：水平还不够，还需修炼方能提交PR -_-||

**Comment by PengJiyuan** [comment]
这个我觉得你可以提交pr啊～微信交流一下，我教你，一会儿邮件发你微信。

**Comment by PengJiyuan** [comment]
Close [#14](https://github.com/PengJiyuan/omg/pull/14)
