### ISSUE TITLE
omg.js.org like landing page

### ISSUE THREAD

**Issue by eaba** [PengJiyuan/omg#16]
Hi
I like you home page here: https://omg.js.org/
Currently, I have a project am working on and on the landing page, instead of the square and the triangles, I want to use, for example, medical tools images animated the way it is. How can I achieve this with OMG?

Thanks

**Comment by PengJiyuan** [comment]
Hi!
This home page is just a simple demo, OMG can do more advanced work!
When you create an omg instance, you can do a lot of things.
```javascript
const stage = omg({
  // You can define canvas size, preload images, enable global scale, enable global translate etc.
  ...settings
});
stage.init();
```
after init, the stage become a complete instance. You can use it to create graph what omg support. If omg's graphs not enough, just use `stage.extend()` to extend your own shapes before `stage.init()`!

After you create a graph, you can simply bind events on the graph,  just simple as DOM.

This is an simple animation demo:

```javascript
const rectangle = stage.rectangle({
  ...settings
});

stage.addChild([rectangle]);
stage.show();

// you can simply animate this graph like this

rectangle.animateTo({
  x: 60,
  y: 100,
  width: 200,
  height: 200,
  rotate: 320,
  ...
}, {
  easing: 'bounceOut',
  duration: 500,
  delay: 500,
  onStart: (keys) => {},
  onUpdate: (keys) => {},
  onFinish: (keys) => {}
});

// This graph will animate to the position you defined, and then animation cancel.
// Don't need worry about the animation performance
// No matter how many animations are on the page, OMG only maintains an animation sequence.

// If you want to animate many graphs in a function, just like this.
stage.animate(() => {
  rect1.x ++;
  rect2.y ++;
  rect3.rotate ++;
  stage.redraw();
});
```

Hope this answer can help you！

**Comment by eaba** [comment]
Yes a bit, but how can i use images in place of rectangles and circles. I saw omg supports image, will this work the way i intend?

**Comment by PengJiyuan** [comment]
Yes, the same way!

```javascript
const image = omg.image({
  ...settings
});

...

image.animateTo({
  ...settigns
});
```

**Comment by eaba** [comment]
Thanks
